EPMS/urls.py
from django.contrib import admin
from django.urls import path,include
from website import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',views.ProductListView.as_view(),name='home'),

    path('account/',include('account.urls')),
    path('userprofilecreate/', views.UserProfileCreateView.as_view(), name='userprofilecreate'),
    path('userprofileupdate/<int:pk>', views.UserProfileUpdateView.as_view(), name='userprofileupdate'),

    path('products/',include('products.urls')),
    path('cart/',include('carts.urls')),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('contactus/',views.contactus,name='contactus'),

    path('passwordresetdone/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('passwordresetconfirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('search/', views.SearchView.as_view(), name='search'),
    path('paytm/', include('payments.urls')),


    



    # path('login/',views.login,name='login'),
    # path('logout/',views.logout,name='logout'),
    # path('register/',views.register,name='register'),
    # path('forgotpassword/',views.forgotpassword,name='forgotpassword'),
    # path('newproduct/',views.newproduct,name='newproduct'),
    # path('products/',views.ProductListView.as_view(),name='products'),
    # path('productdetails/<int:pk>',views.ProductDetailView.as_view(),name='productdetails'),
    # path('newproduct/',views.ProductCreateView.as_view(), name='newproduct'),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path
from account import views
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('otpverify/',views.otpverify, name='otpverify'),
    path('passwordreset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),    
]

carts/urls.py
from django.contrib import admin
from django.urls import path
from carts import views


app_name = 'cart'
urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_to_cart/<int:pk>',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:pk>',views.remove_from_cart,name='remove_from_cart'),
    path('update_cart/<int:pk>',views.update_cart,name='update_cart'),
    
]

products/urls.py
from django.contrib import admin
from django.urls import path,include
from products import views

app_name = 'product'
urlpatterns = [

    path('products/',views.ProductListView.as_view(),name='products'),
    path('productdetails/<int:pk>',views.ProductDetailView.as_view(),name='productdetails'),
    path('newproduct/',views.ProductCreateView.as_view(), name='newproduct'),
    path('updateproduct/<int:pk>',views.ProductUpdateView.as_view(), name='updateproduct'),
    path('Deleteproduct/<int:pk>',views.ProductDeleteView.as_view(), name='deleteproduct'),

]

carts/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from django.utils import timezone
# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    productquantity = models.PositiveIntegerField(default=1)
    total_price = models.PositiveIntegerField(default=0)
    added_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.user.username

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from website.models import UserProfile
# Create your models here.


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    productname = models.CharField(max_length=256)
    productimage = models.ImageField(upload_to='newproduct/image/')
    productprice = models.FloatField()
    productdescription = models.CharField(max_length=256)
    productquantity = models.PositiveIntegerField(default=1)
    productaddress = models.CharField(max_length=256)
    hugeproduct = models.BooleanField(default=False)

    def __str__(self):
        return self.productname

    def get_absolute_url(self):
        return reverse('home')

website/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

class UserProfile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    mobilenumber = models.PositiveIntegerField(validators=[MaxValueValidator(9999999999)])
    address = models.CharField(max_length=356)
    created = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + ' ' + self.fname + self.lname

    def get_absolute_url(self):
        return reverse('userprofilecreate')


###################################################################################################################


class ContactUs(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    mobilenumber = models.PositiveIntegerField(validators=[MaxValueValidator(9999999999)])
    subject = models.CharField(max_length=356)
    message = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('contactus')


###############################################################################################################        


# class Product(models.Model):
#     productname = models.CharField(max_length=50)
#     productimage = models.ImageField(upload_to='newproduct/image/')
#     productprice = models.IntegerField()
#     productdescription = models.CharField(max_length=500)

#     def __str__(self):
#         return self.productname


################################################################################################################################


# class Product(models.Model):
#     productname = models.CharField(max_length=256)
#     productimage = models.ImageField(upload_to='newproduct/image/')
#     productprice = models.IntegerField()
#     productdescription = models.CharField(max_length=256)

#     def __str__(self):
#         return self.productname

#     def get_absolute_url(self):
#         return reverse('home')

products/forms.py
from django import forms
from products import models

class NewProductForm(forms.ModelForm):
    class Meta():
        model = models.Product
        fields = '__all__'

carts/views.py
from django.shortcuts import render,redirect
from products.models import Product
from django.contrib.auth.models import User
from carts.models import Cart
from django.contrib import messages
# Create your views here.

def add_to_cart(request,pk):
    #print(pk)
    product = Product.objects.get(pk=pk)
    user = User.objects.get(username=request.user.username)
    if Cart.objects.filter(product=product).exists():
        for object in Cart.objects.filter(product=product):
            productquantity = object.productquantity + 1
        Cart.objects.filter(product=product).update(productquantity=productquantity)
    else:
        Cart.objects.create(user=user,product=product,total_price=product.productprice)
    return redirect('cart:cart')

def cart(request):
    net_total_price = 0
    user = User.objects.get(username=request.user.username) 
    carts = Cart.objects.filter(user=user)
    item_in_carts = carts.count()
    for i in carts:
        subtotal = 0
        subtotal = subtotal + i.productquantity * i.product.productprice
        i.total_price =subtotal
        i.save()
        net_total_price = net_total_price + i.total_price
    
        
    request.session['total-cart'] = len(carts)
    return render(request,'cart.html',{'carts':carts,'net_total_price':net_total_price, 'item_in_carts':item_in_carts})

def update_cart(request,pk):
    product = Product.objects.get(pk=pk)
    user = User.objects.get(username=request.user.username)
    cart = Cart.objects.get(user=user,product=product)
    action = request.GET.get('action')
    if action == "decrease":
        if cart.productquantity == 1:
            messages.info(request, 'Oops! You can remove product by using \' REMOVE \' button.' )
        else:
            cart.productquantity = cart.productquantity - 1
            cart.save()
    else:
        if cart.productquantity == cart.product.productquantity:
            messages.info(request, 'Only'+ ' ' + str(cart.product.productquantity) + ' ' + str(cart.product.productname) + ' ' + 'are' + ' ' + 'available.')
        else:
            cart.productquantity = cart.productquantity + 1
            cart.save()
    return redirect('cart:cart')


def remove_from_cart(request,pk):
    product = Product.objects.get(pk=pk)
    user = User.objects.get(username=request.user.username)
    cart = Cart.objects.get(user=user,product=product)
    cart.delete()
    return redirect('cart:cart')

products/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from products import forms
from products import models
from django.views.generic import (CreateView, ListView, UpdateView, DeleteView, DetailView)
from django.contrib.auth.models import User, auth
from django.urls import reverse_lazy
from django.contrib import messages
from website.models import UserProfile

# Create your views here.


class ProductCreateView(CreateView):
    model = models.Product
    fields = '__all__'
    template_name = 'newproduct.html'

    def post(self,request):
        form = forms.NewProductForm()
        if request.method == 'POST':
            form = forms.NewProductForm(request.POST, request.FILES)
            if form.is_valid():
                product = form.save(commit=False)
                product.user = request.user
                
                if 'productimage' in request.FILES:
                    product.productimage = request.FILES['productimage']

                product.save()
                return redirect('home')
            else:
                #print(form.errors)
                messages.error(request,'Invalid Details. Please try again.')
                return render(request, 'newproduct.html',{'form': form})
        else:
            return render(request, 'newproduct.html', {'form': form})

    
##########################################################################################################


class ProductListView(ListView):
    model = models.Product
    template_name = 'products.html'
    context_object_name = 'objects'
    paginate_by = 4
    paginate_orphans = 1
    queryset = model.objects.all()


##########################################################################################################


class ProductDetailView(DetailView):
    model = models.Product
    #fields = '__all__'
    template_name = 'productdetails.html'


##########################################################################################################


class ProductUpdateView(UpdateView):
    model = models.Product
    fields = ['productprice','productdescription','productimage','productname', 'productaddress', 'hugeproduct','productquantity']
    template_name = 'newproduct.html'



##########################################################################################################


class ProductDeleteView(DeleteView):
    model = models.Product
    template_name = 'deleteproduct.html'
    success_url = reverse_lazy('product:products')


##########################################################################################################

templates/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us | E-Plastic Management System</title>
	<link rel="stylesheet" href="{% static '/css/stylesheet.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/css/aboutus.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/stylesheet.css' %}">
</head>
<body style="background:radial-gradient(#fff,#29A3F7);">

	<div class="container">
		<div class="navbar">
			<div class="logo">
				<a href="{% url 'home' %}"><img src="{% static 'image/logo.png' %}" width="55px"></a>
			</div>
			<nav>
				<ul id="MenuItems">
				<li><a href="{% url 'home' %}">Home</a></li>
				<li><a href="{% url 'aboutus' %}">About</a></li>
				<li><a href="{% url 'product:products' %}">Products</a></li>

				{% if user.is_authenticated %}
					<li><a href="{% url 'product:newproduct' %}">Sell</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Sell</a></li>
				{% endif %}
				<li><a href="{% url 'contactus' %}">Contact Us</a></li>

				{%  if user.is_authenticated %}
					<li>Welcome,
						<a href="{% url 'userprofilecreate'  %}" style="color: #fff;">{{user.username}}</a>
					</li>
					<li><a href="{% url 'account:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Login</a></li>
				{% endif %}
				</ul>
			</nav>
			<a href="{% url 'cart:cart' %}"><img src="{% static 'image/cart.png' %}" width="30px" height="30px"></a>
			<img src="{% static 'image/menu.png' %}" class="menu-icon" onclick="menutoggle()">
		</div>
   

    <div class="about">
        <div class="inner-section">
            <h1>About Us</h1>
            <p class="text" style="color: black;">
                We are the students of computer engineering trying to solve the global day-to-day problem by providing a platform or a solution for that particular problem.
                Here as the name suggests E-Plastic Management System is used for the collection of plastic waste material from the customer, local collector, so on.
                The customer can define the details about which type of  plastic waste is having. The customer can get the money by giving away the plastic waste. E-plastic Management System is for selling and buying the plastic waste material.
                The main purpose of the E-Plastic Management System is to provide a platform so that the human society can sell and buy the resuable and recyclable plastic materials.
                This will reduce the plastic waste from household, company, industries, city, etc.
                The Environment Pollution as well as plastic production will reduce.
                This technique could eliminate plastic disposal costs, reduce raw material costs and provide income from a salable plastic waste. 
                
            </p>
            <h1>Our Vision</h1>
            <p class="text" style="color: black;">
                India to become a leading Circular Economy where Nothing is Waste. 
            </p>
            
            <div class="skills">
                <a href="{% url 'contactus' %}" class="btn">Contact Us</a>
            </div>
        </div>    
    </div>
</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>E-Plastic Management System </title>
	<link rel="stylesheet" href="{% static '/css/stylesheet.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

</head>
</head>
<body>

	<div class="container">
		<div class="navbar">
			<div class="logo">
				<a href="{% url 'home' %}"><img src="{% static 'image/logo.png' %}" width="55px"></a>
			</div>
			<nav>
				<ul id="MenuItems">
				<li><a href="{% url 'home' %}">Home</a></li>
				<li><a href="{% url 'aboutus' %}">About</a></li>
				<li><a href="{% url 'product:products' %}">Products</a></li>

				{% if user.is_authenticated %}
					<li><a href="{% url 'product:newproduct' %}">Sell</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Sell</a></li>
				{% endif %}
				<li><a href="{% url 'contactus' %}">Contact Us</a></li>

				{%  if user.is_authenticated %}
					<li>Welcome, 
						<a href="{% url 'userprofilecreate'  %}">{{user.username}}</a>
					</li>
					<li><a href="{% url 'account:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Login</a></li>
				{% endif %}
				</ul>
			</nav>
			<a href="{% url 'cart:cart' %}"><img src="{% static 'image/cart.png' %}" width="30px" height="30px"></a>
			<img src="{% static 'image/menu.png' %}" class="menu-icon" onclick="menutoggle()">
			
		</div>
		
    </div>
	
<!---------------------------------------------------------------------------------------------------------------->

{% block content %}


{% endblock %}





<!------------------------------------------------------------------------------------------------------------------------->


<div class="footer">
	<div class="container">
		<div class="row">
			<div class="footer-col-1">
				<h3><a href="https://www.ecosia.org/?c=en"><img src="{% static 'image/ecosia-logo.png' %}" style="width:50px;"></a></h3>
				<p>Download the app for Android.</p>
				<div class="app-logo">
					<a href="https://play.google.com/store/apps/details?id=com.ecosia.android"><img src="{% static 'image/play-store.png' %}"></a>
					<a href="https://apps.apple.com/us/app/ecosia/id670881887"><img src="{% static 'image/app-store.png' %}"></a>
				</div>
			</div>
			<div class="footer-col-2">
				<img src="{% static 'image/logo.png' %}"><h4 style="color:white;">E-Plastic</h4>
				<p>Our purpose is to  manage plastic waste by means of <br> recyclying and reusing plastic and avoid pollution.</p>
			</div>
			<div class="footer-col-3">
				<h3>Awareness Links</h3>
				<ul>
					<li><a href="https://www.unenvironment.org/interactive/beat-plastic-pollution/">unenvironment</a></li>
					<li><a href="http://onemoregeneration.org/2011/10/22/ska-academy-of-art-and-designs-plastic-awareness-program/">onemoregeneration</a></li>
					<li><a href="https://tunza.eco-generation.org/ambassadorReportView.jsp?viewID=48258">Tunza Eco Generation</a></li>
					<li><a href="https://www.nrdc.org/stories/10-ways-reduce-plastic-pollution">nrdc</a></li>
				</ul>
			</div>
			<div class="footer-col-4">
				<h3>Follow Us</h1>
				<ul>
					<li><a href="https://www.facebook.com/">Facebook</a></li>
					<li><a href="https://twitter.com/?lang=en">Twitter</a></li>
					<li><a href="https://www.instagram.com/">Instagram</a></li>
					<li><a href="https://www.youtube.com/">Youtube</a></li>
				</ul>
			</div>
		</div>
		<hr>
			<p class="copyright">Copyright 2020&copy;</p>
	</div>
</div>

<script src="{% static '/js/home.js' %}"></script>
</body>
</html>

templates/base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Home | E-Plastic Management System </title>
	<link rel="stylesheet" href="{% static '/css/stylesheet.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</head>
</head>
<body>

<div class="header">
	<div class="container">
		<div class="navbar">
			<div class="logo">
				<a href="{% url 'home' %}"><img src="{% static 'image/logo.png' %}" width="55px"></a>
			</div>
			<nav>
				<ul id="MenuItems">
				<li><a href="{% url 'home' %}">Home</a></li>
				<li><a href="{% url 'aboutus' %}">About</a></li>
				<li><a href="{% url 'product:products' %}">Products</a></li>

				{% if user.is_authenticated %}
					<li><a href="{% url 'product:newproduct' %}">Sell</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Sell</a></li>
				{% endif %}

				<li><a href="{% url 'contactus' %}">Contact Us</a></li>

				{%  if user.is_authenticated %}
					<li>Welcome,
							<a href="{% url 'userprofilecreate'  %}" style="color: #fff;">{{user.username}}</a>
					</li>

					<li><a href="{% url 'account:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Login</a></li>
				{% endif %}
				</ul>
			</nav>
			<a href="{% url 'cart:cart' %}"><img src="{% static 'image/cart.png' %}" width="30px" height="30px"></a>
			<img src="{% static 'image/menu.png' %}" class="menu-icon" onclick="menutoggle()">
			
		</div>

{% block content %}


{% endblock %}






<!----------------------------------------------------------------------------------------------------------->
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="footer-col-1">
				<h3><a href="https://www.ecosia.org/?c=en"><img src="{% static 'image/ecosia-logo.png' %}" style="width:50px;"></a></h3>
				<p>Download the app for Android.</p>
				<div class="app-logo">
					<a href="https://play.google.com/store/apps/details?id=com.ecosia.android"><img src="{% static 'image/play-store.png' %}"></a>
					<a href="https://apps.apple.com/us/app/ecosia/id670881887"><img src="{% static 'image/app-store.png' %}"></a>
				</div>
			</div>
			<div class="footer-col-2">
				<img src="{% static 'image/logo.png' %}"><h4 style="color:white;">E-Plastic</h4>
				<p>Our purpose is to  manage plastic waste by means of <br> recyclying and reusing plastic and avoid pollution.</p>
			</div>
			<div class="footer-col-3">
				<h3>Awareness Links</h3>
				<ul>
					<li><a href="https://www.unenvironment.org/interactive/beat-plastic-pollution/">unenvironment</a></li>
					<li><a href="http://onemoregeneration.org/2011/10/22/ska-academy-of-art-and-designs-plastic-awareness-program/">onemoregeneration</a></li>
					<li><a href="https://tunza.eco-generation.org/ambassadorReportView.jsp?viewID=48258">Tunza Eco Generation</a></li>
					<li><a href="https://www.nrdc.org/stories/10-ways-reduce-plastic-pollution">nrdc</a></li>
				</ul>
			</div>
			<div class="footer-col-4">
				<h3>Follow Us</h1>
				<ul>
					<li><a href="https://www.facebook.com/">Facebook</a></li>
					<li><a href="https://twitter.com/?lang=en">Twitter</a></li>
					<li><a href="https://www.instagram.com/">Instagram</a></li>
					<li><a href="https://www.youtube.com/">Youtube</a></li>
				</ul>
			</div>
		</div>
		<hr>
			<p class="copyright">Copyright 2020&copy;</p>
	</div>
</div>

<script src="{% static '/js/home.js' %}">
</script>




</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="account-page">
	<div class="container">
		<div class="row">
			<div class="col-2">
				<img src="{% static 'image/plastic.png' %}" alt="" width="100%">
			</div>
			<div class="col-2">
				<div class="form-container">
					<div class="form-btn">
						<span>Login</span>
						<hr id="indicator">
					</div>
					<form action="{% url 'account:login' %}" method="POST" id="login-form">
						{% csrf_token %}
						<input type="text" placeholder="Username" name="username"/>
						<input type="password" placeholder="Password" name="password"/>
						{% for message in messages %}
							<div style="color:red;">{{message}}</div>
						{% endfor %}
						<button type="submit" class="btn">Login</button>
						
						<a href="{% url 'account:password_reset' %}">Forgot Password /</a><a href="{% url 'account:register' %}"> Register</a>
					</form>
					
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="account-page">
	<div class="container">
		<div class="row">
			<div class="col-2">
				<img src="{% static 'image/plastic.png' %}" alt="" width="100%">
			</div>
			<div class="col-2">
				<div class="form-container" style="height:300px;">
					<div class="form-btn">
						<span>Reset Password</span>
						<hr id="indicator">
					</div>					
					<form method="POST" id="reg-form">
						{% csrf_token %}
						<input type="email" placeholder="Enter your registered email" name="email" autocomplete="email" required_id="id_email" maxlength="254"/>
						<!--<input type="email" placeholder="Email" name="email"/>
						<input type="password" placeholder="New Password" name="password"/>
						<input type="password" placeholder="Confirm New Password" name="cnf_password"/>
						{% for message in messages %}
							<div style="color:red;">{{message}}</div>
						{% endfor %}-->
						<button type="submit" class="btn">Request Reset Password</button>
						<!--<a href="{% url 'account:login' %}"> Login</a>-->
					</form>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>E-Plastic Management System </title>
	<link rel="stylesheet" href="{% static '/css/stylesheet.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://code.jquery.com/jquery-3.5.1.min.js">
</head>
</head>
<body>

	<div class="container">
		<div class="navbar">
			<div class="logo">
				<a href="{% url 'home' %}"><img src="{% static 'image/logo.png' %}" width="55px"></a>
			</div>
			<nav>
				<ul id="MenuItems">
				<li><a href="{% url 'home' %}">Home</a></li>
				<li><a href="{% url 'aboutus' %}">About</a></li>
				<li><a href="{% url 'product:products' %}">Products</a></li>

				{% if user.is_authenticated %}
					<li><a href="{% url 'product:newproduct' %}">Sell</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Sell</a></li>
				{% endif %}
				<li><a href="{% url 'contactus' %}">Contact Us</a></li>

				{%  if user.is_authenticated %}
					<li>Welcome, {{user.username}}</li>>
					<li><a href="{% url 'account:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'account:login' %}">Login</a></li>
				{% endif %}
				</ul>
			</nav>
			<a href="{% url 'cart:cart' %}"><img src="{% static 'image/cart.png' %}" width="30px" height="30px"></a>
			<img src="{% static 'image/menu.png' %}" class="menu-icon" onclick="menutoggle()">
		</div>
    </div>

    <div style="margin-left: 160px; margin-top: 50px; font-size: 16px;">
        An email has been send with instructions to reset your password
    </div><br>
	<a href="https://mail.google.com/" style="margin-left: 160px; margin-top: 50px; font-size: 16px; color: green;">Go to mail</a>
    
<!------------------------------------------------------------------------------------------------------>


<script src="{% static '/js/home.js' %}"></script>


</body>
</html>